name: sitecore_flutter
description: A Flutter app for Sitecore Headless.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  equatable: ^2.0.0
  rxdart: ^0.26.0
  flutter_bloc: ^7.0.0
  json_class: ^2.0.0
  logging: ^1.0.1
  meta: ^1.3.0
  uuid: ^3.0.4
  child_builder: ^2.0.0
  flutter_html: ^2.0.0
  shared_preferences: ^2.0.5
  hex: ^0.2.0
  google_fonts: ^2.1.0

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/onboard-background.png
   - assets/img/logo-android.png
   - assets/img/logo-ios.png
   - assets/img/profile-screen-avatar.jpg
   - assets/img/profile-screen-bg.png